version: '2'

services:
  userstudy_db:
    image: postgres:9.5
    ports:
      - '5432:5432'
    volumes:
      - 'pg_dev_container:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_DB: userstudy_dev
  
volumes:
  pg_dev_container: